# Generated by Django 5.1.6 on 2025-02-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='data',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='snils',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='doctors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
