# Generated by Django 5.1.6 on 2025-03-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0003_contact_doctor_symptom_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='doctors',
        ),
        migrations.AddField(
            model_name='appointment',
            name='custom_symptoms_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='related_symptoms',
            field=models.ManyToManyField(blank=True, related_name='related_doctors', to='doctor_app.symptom'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='symptoms',
            field=models.ManyToManyField(blank=True, to='doctor_app.symptom'),
        ),
    ]
