# Generated by Django 5.1.6 on 2025-03-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0005_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='related_symptoms',
            field=models.ManyToManyField(blank=True, to='doctor_app.symptom'),
        ),
    ]
