# Generated by Django 5.1.6 on 2025-03-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0006_alter_doctor_related_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='related_symptoms',
            field=models.ManyToManyField(blank=True, related_name='related_doctors', to='doctor_app.symptom'),
        ),
        migrations.CreateModel(
            name='DoctorSymptomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('doctors', models.ManyToManyField(related_name='symptom_groups', to='doctor_app.doctor')),
                ('symptoms', models.ManyToManyField(related_name='doctor_groups', to='doctor_app.symptom')),
            ],
        ),
    ]
